#define SOUND_SUPPORTS_AIFF   1
#define SOUND_SUPPORTS_AU     1
#define SOUND_SUPPORTS_MIKMOD 1
#define SOUND_SUPPORTS_RAW    1
#define SOUND_SUPPORTS_SHN    1
#define SOUND_SUPPORTS_VOC    1
#define SOUND_SUPPORTS_WAV    1

/*#define SOUND_SUPPORTS_MP3    1*/

#define SOUND_SUPPORTS_MPGLIB 1

#define SUPPORT_PHYSFS 0

#define SOUND_SUPPORTS_QUICKTIME 1